[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/products"
  to = "/.netlify/functions/products"
  status = 200

[[redirects]]
  from = "/api/admin/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/admin/products"
  to = "/.netlify/functions/admin-products"
  status = 200

[[redirects]]
  from = "/api/admin/toggle"
  to = "/.netlify/functions/toggle"
  status = 200

[[redirects]]
  from = "/api/admin/delete"
  to = "/.netlify/functions/delete"
  status = 200

[[redirects]]
  from = "/api/image"
  to = "/.netlify/functions/image"
  status = 200
